### ISSUE TITLE
[IOS Device] A RenderFlex overflowed by pixels on bottom

### ISSUE THREAD

**Issue by shaffa476** [FaizaFaisal/Hemo-Bank#1]
**Bug Report**

**Describe the Bug**
Running the app on android devices, it works perfectly fine but on IOS devices, there is renderflex error at the bottom of every screen. 

**Steps to reproduce the behavior on IOS device:**

- Make app
- Run on IOS device

**Comment by FaizaFaisal** [comment]
This happens when you have a  screen with content more than the device's specified height. 
Using  **_height = MediaQuery.of(context).size.height fixes this issue._**
